#%RAML 0.8
title: PagerDuty Integration
version: 2010-04-15
baseUri: https://events.pagerduty.com/generic/{version}/
securitySchemes:
  - basic: !include securitySchemes/basic.raml
  - tokenSchema: !include securitySchemes/tokenSchema.raml
schemas:
  - integrationResponse: !include schemas/integrationResponse-schema.json
  - integrationRequest: !include schemas/integrationRequest-schema.json
/create_event.json: 
  description: |
    The API was designed to allow you to easily integrate a monitoring system with a Service in PagerDuty. Monitoring systems generally send out events when problems are detected and when these problems have been resolved (fixed). Some more advanced systems also understand the concept of acknowledgements: problems can be acknowledged by an engineer to signal he or she is working on fixing the issue.
    
    Since monitoring systems emit events, the API is based around accepting events. Incoming events (sent via the API) are routed to a PagerDuty service and processed. They may result in a new incident being created, or an existing incident being acknowledged or resolved.
    
    The same event-based API can also be used to integrate a PagerDuty service with ticketing systems and various other software tools.
  post: 
    description: |
      Send one of the desired events.
      
      TRIGGER
      Your monitoring tools should send PagerDuty a trigger event to report a new or ongoing problem. When PagerDuty receives a trigger event, it will either open a new incident, or add a new trigger log entry to an existing incident, depending on the provided 'incident_key'.
      
      Trigger object params
      |Name|Type|Required|Description|
      |---|---|---|---|
      |service_key|String|Yes|The GUID of one of your "Generic API" services. This is the "service key" listed on a Generic API's service detail page.|
      |event_type|String|Yes|Set this to "trigger".|
      |description|String|Yes|A short description of the problem that led to this trigger. This field (or a truncated version) will be used when generating phone calls, SMS messages and alert emails. It will also appear on the incidents tables in the PagerDuty UI. The maximum length is 1024 characters.|
      |incident_key|String|No|Identifies the incident to which this trigger event should be applied. If there's no open (i.e. unresolved) incident with this key, a new one will be created. If there's already an open incident with a matching key, this event will be appended to that incident's log. The event key provides an easy way to "de-dup" problem reports. If this field isn't provided, PagerDuty will automatically open a new incident with a unique key.|
      |client|String|No|The name of the monitoring client that is triggering this event.|
      |client_url|String|No|The URL of the monitoring client that is triggering this event.|
      |details|Object|No|An arbitrary JSON object containing any data you'd like included in the incident log.|
      
      ACKNOWLEDGE
      Acknowledge events cause the referenced incident to enter the acknowledged state. While an incident is acknowledged, it won't generate any additional notifications, even if it receives new trigger events. Your monitoring tools should send PagerDuty an acknowledge event when they know someone is presently working on the problem.
      
      Acknowledge object params      
      |Name|Type|Required| Description|
      |---|---|---|---|
      |service_key|String|Yes|The GUID of one of your "Generic API" services. This is the "service key" listed on a Generic API's service detail page.|
      |event_type|String|Yes|Set this to "acknowledge".|
      |incident_key|String|Yes|Identifies the incident to acknowledge. This should be the incident_key you received back when the incident was first opened by a trigger event. Acknowledge events referencing resolved or nonexistent incidents will be discarded.|
      |description|String|No|Text that will appear in the incident's log associated with this event.|
      |details|Object|No|An arbitrary JSON object containing any data you'd like included in the incident log.|
      
      RESOLVE
      Resolve events cause the referenced incident to enter the resolved state. Once an incident is resolved, it won't generate any additional notifications. New trigger events with the same 'incident_key' as a resolved incident won't re-open the incident. Instead, a new incident will be created. Your monitoring tools should send PagerDuty a resolve event when the problem that caused the initial trigger event has been fixed.
      
      Resolve object params
      |Name|Type|Required| Description|
      |---|---|---|---|
      |service_key|String|Yes|The GUID of one of your "Events API" services. This is the "service key" listed on a Generic API's service detail page.|
      |event_type|String|Yes|Set this to "resolve".|
      |incident_key|String|Yes|Identifies the incident to resolve. This should be the incident_key you received back when the incident was first opened by a trigger event. Resolve events referencing resolved or nonexistent incidents will be discarded.|
      |description|String|No|Text that will appear in the incident's log associated with this event.|
      |details|Object|No|An arbitrary JSON object containing any data you'd like included in the incident log.|
    body: 
      application/json: 
        schema: integrationRequest
        example: !include examples/integrationRequest-example.json
    responses: 
      200: 
        description: OK - The event has been accepted by PagerDuty. See below for details.
        body: 
          application/json: 
            schema: integrationResponse
            example: !include examples/integrationResponse-example.json
      400: 
        description: Bad Request - Check that the JSON is valid. See below for details.
      403: 
        description: Forbidden - Too many API calls at a time.
      500: 
        description: |
          Or other 5XX
          Internal Server Error - the PagerDuty server experienced an error while processing the event.
documentation: 
  - title: Headline
    content: !include docs/integration/headline.md