description: |
  Twitter offers applications the ability to issue authenticated requests on
  behalf of the application itself (as opposed to on behalf of a specific user).
type: OAuth 1.0
settings: 
  requestTokenUri: https://api.twitter.com/oauth/request_token
  authorizationUri: https://api.twitter.com/oauth/authorize
  tokenCredentialsUri: https://api.twitter.com/oauth/access_token
