queryParameters: 
  callback: 
    description: JS method name for JSONP callbacks.
  indent: 
    description: Whether to indent the JSON results or not.
  query: 
    description: Query term to search for.
    example: query=bob
