queryParameters: 
  lang: 
    description: |
      The code of the language with which to run the query. Default is 'en'.
      The language you'd like the content in - a Freebase /type/lang language key. 
      Languages for names and values. First language is used for display. Default is 'en'.
