queryParameters: 
  limit: 
    description: |
      Maximum number of candidates to return. Defaults to 3.
      The maximum number of property values to return for each property. Must be a positive integer. Default is 10.
      Maximum number of results to return. By default, 20 matches in decreasing order of relevance are returned, if that many exist. Fewer or more matches may be requested by using the limit parameter with a different value. (Example.)
