headers: 
  x-ms-date: 
    description: |
      Specifies the Coordinated Universal Time (UTC) for the request.
      For more information, see Authentication for the Windows Azure Storage Services.
      Presence one of either "Date" or "x-ms-date" is required.
  Date: 
    description: |
      Same as the "x-ms-date" header.
      Presence one of either "Date" or "x-ms-date" is required.
  x-ms-version: 
    description: |
      Specifies the version of the operation to use for this request.
      For more information, see Versioning for the Blob, Queue, and Table Services in Windows Azure.
  x-ms-client-request-id: 
    description: |
      Provides a client-generated, opaque value with a 1 KB character limit that
      is recorded in the analytics logs when storage analytics logging is enabled.
      Using this header is highly recommended for correlating client-side activities
      with requests received by the server. For more information,
      see About Storage Analytics Logging and Windows Azure Logging --
      Using Logs to Track Storage Requests.
responses: 
  200?: 
    headers: 
      x-ms-version: 
        description: Indicates the version of the Table service used to execute the request. This header is returned for requests made against version 2009-09-19 and later.
      x-ms-request-id: 
        description: This header uniquely identifies the request that was made and can be used for troubleshooting the request. For more information, see Troubleshooting API Operations.
      Date: 
        description: A UTC date/time value generated by the service that indicates the time at which the response was initiated.
  202?: 
    headers: 
      x-ms-version: 
        description: Indicates the version of the Table service used to execute the request. This header is returned for requests made against version 2009-09-19 and later.
      x-ms-request-id: 
        description: This header uniquely identifies the request that was made and can be used for troubleshooting the request. For more information, see Troubleshooting API Operations.
      Date: 
        description: A UTC date/time value generated by the service that indicates the time at which the response was initiated.
  204?: 
    headers: 
      x-ms-version: 
        description: Indicates the version of the Table service used to execute the request. This header is returned for requests made against version 2009-09-19 and later.
      x-ms-request-id: 
        description: This header uniquely identifies the request that was made and can be used for troubleshooting the request. For more information, see Troubleshooting API Operations.
      Date: 
        description: A UTC date/time value generated by the service that indicates the time at which the response was initiated.
