queryParameters: 
  comp: 
    description: ""
    required: true
    enum: [ stats , properties ]
  restype: 
    required: true
    enum: [ service ]
  timeout: 
    description: The parameter is expressed in seconds.
    type: integer
