body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      description: 
        description: An arbitrary string which you can attach to the invoice item. The description is displayed in the invoice for easy tracking. This will be unset if you POST an empty value.
      metadata: 
        description: A set of key/value pairs that you can attach to an item. It can be useful for storing additional information about the item in a structured format. You can unset individual keys if you POST an empty value for that key. You can clear all keys if you POST an empty value for metadata.
