queryParameters: 
  target_id: 
    description: The ID of the object to which user_current will subscribe/unsubscribe. Must be used in combination with target_type.
    required: true
  target_type: 
    description: The target type (user or tag(legacy for topic)) to which user_current will subscribe/unsubscribe. Must be used in combination with target_id.
    required: true
