usage: |
  This resourceType should be used for any resource that is named "delete" and has a POST action that allows deleting of a resource.
type: wordpressResourceWithHttpEnvelopeSupport
description: |
  Deletes this resorce.
post: 
