usage: |
  This resourceType should be used for any resource that is placed inside a "list" resource, has an URI parameter and has a GET action that allows fetching of a resource by it's ID.
type: wordpressResourceWithHttpEnvelopeSupport
description: |
  Returns this resorce.
get: 
