usage: |
  This resourceType should be used for any resource that is named "new" and has a POST action that allows creating of a resource.
type: wordpressResourceWithHttpEnvelopeSupport
description: |
  Creates new resorce.
post: 
