post?: 
  responses: 
    200: 
      body: 
        application/json: 
          example: !include ../examples/http_envelope.json
get?: 
  responses: 
    200: 
      body: 
        application/json: 
          example: !include ../examples/http_envelope.json
type: wordpressResource
