queryParameters: 
  limit: 
    description: The maximum number of payments to return in a single response. This value cannot exceed 200. This value is always an integer.
    default: 100
    example: 100
  order: 
    description: The order in which payments are listed in the response.
    enum: [ DESC , ASC ]
    default: ASC
    example: ASC
