queryParameters: 
  rel: 
    description: List endpoints might paginate the results they return. This means that instead of returning all results in a single response, these endpoints might return some of the results, along with a response header that links to the next set of results.
    enum: [ next ]
