body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      total: 
        description: The offset of the first record returned. Default is 0.
        type: integer
      offset: 
        description: The number of records returned. Default (and max limit) is 100 for most APIs.
        type: integer
