queryParameters: 
  maxResults: 
    description: |
      Maximum number of entries returned on one result page. By default the value is 100 entries. The page size can never be larger than 250 entries. Optional.
      Maximum number of events returned on one result page. By default the value is 250 events. The page size can never be larger than 2500 events. Optional.
    type: integer
    default: 100
    example: 50
