queryParameters: 
  sendNotifications: 
    description: |
      Whether to send notifications about the creation of the new event. Optional. The default is False.
    type: boolean
    default: false
    example: true
