queryParameters: 
  page: 
    description: "The page of the result set to display."
  per_page: 
    description: |
      The number of sets to display per page (must be between 1 and 50).
      
      The number of classes to display per page (must be between 1 and 50).
