description: Schema which requires Application ID and REST API Key
type: x-header-schema
describedBy: 
  headers: 
    X-Parse-Application-Id: 
      description: Id of the application
      required: true
      example: GzBxtflDl76RdiZFLujo4uNVxS7MIZXbEy6D3Tle
    X-Parse-REST-API-Key: 
      description: REST API key of the application.
      required: true
      example: UugJz3YVpU0gKgK7OfIYQQAntOxFGKPK615Qmjc9
