description: Schema which requires Application ID, REST API Key and Session Token
type: x-header-schema
describedBy: 
  headers: 
    X-Parse-Application-Id: 
      description: Id of the application
      required: true
      example: GzBxtflDl76RdiZFLujo4uNVxS7MIZXbEy6D3Tle
    X-Parse-REST-API-Key: 
      description: REST API key of the application.
      required: true
      example: UugJz3YVpU0gKgK7OfIYQQAntOxFGKPK615Qmjc9
    X-Parse-Session-Token: 
      description: Session token
      required: true
      example: pnktnjyb996sj4p156gjtp4im
