queryParameters: 
  filter: 
    description: Specifies a filter for items within a folder. The value IsInMyFileSync filters out the items that aren’t synced in a folder.
  page: 
    description: An integer specifying a page of items. The default value is 0, which returns the first page.
  pageSize: 
    description: "Specifies the number of items per page. Valid values are from 1 through 100. If you don't specify a size, the default is 25."
