queryParameters: 
  page: 
    description: Specifies the number of the page you want returned.
    type: integer
    example: 5
  pageSize: 
    description: "Specifies the number of items per page. Valid values are from 1 through 100. If you don't specify a size, the default is 25."
    type: integer
    default: 25
    example: 5
