queryParameters: 
  visibility: 
    description: |
      Specifies the visibility behavior of a flag for various user types. One of these values:
      ModeratorsOnly—The flag is visible only to users with moderation permissions on the flagged element or item.
      SelfAndModerators—The flag is visible to the creator of the flag and to users with moderation permissions on the flagged element or item.
    enum: [ SelfAndModerators , ModeratorsOnly ]
    example: ModeratorsOnly
