queryParameters: 
  status: 
    description: Only users with the “Manage Network” permission enabled can see communities with an Inactive status.
    enum: 
      - Live
      - Inactive
      - UnderConstruction
