is: [ allowsBasicAuthentication ]
get: 
  description: Retreive <<objectType>> by objectId
  securedBy: [ commonSchema ]
put: 
  description: Update <<objectType>>
  responses: 
    200: 
      body: 
        application/json: 
          schema: collectionPutResponse
          example: !include ../examples/collectionPutResponse.json
delete: 
  description: |
    Delete <<objectType>> by objectId
  responses: 
    200: 
  securedBy: [ commonSchema ]
