description: |
  Access to the AccuWeather API requires an API key.  Contact sales@accuweather.com to receive an API key. 
type: x-API-Key-Signatures
describedBy: 
  queryParameters: 
    key: 
      description: Your unique API key
      required: true
      example: ABDE12456AB2324445
