description: This API endpoint returns a list of values for each of the requested metrics. The list of available metrics can be returned using the Metric Name API endpoint.
queryParameters: 
  names[]: 
    description: Retrieve specific metrics by name
    required: true
    repeat: true
  values[]: 
    description: Retrieve specific metric values
    repeat: true
  from: 
    description: Retrieve metrics after this time
  to: 
    description: Retrieve metrics before this time
  summarize: 
    description: Summarize the data
    type: boolean
