description: |
  All requests, other than form POSTs, should be sent using basic authentication.
type: Basic
describedBy: 
  headers: 
    Authorization: 
      description: |
        Example of Authorization header:
        Authorization: Basic BDOM0dF1WeYYjUQ5TZzMQEE74Y5Ef2x55YtlOp0ES1yMzQ=
