queryParameters: 
  address_city: 
    description: The city name of the customer. This is automatically normalized.
  address_country_code: 
    description: The country of the customer. Should be of the ISO code form.
  address_postal_code: 
    description: |
      The postal code of the person. Also known as a ZIP code.
      The country of the customer. Should be of the ISO code form.
  address_street1: 
    description: The primary street address of the customer. This is automatically normalized.
  address_street2: 
    description: The second address line typically used for apartment or suite numbers. This is automatically normalized.
  address_subdivision: 
    description: |
      The subdivision of the entered country. For instance in the United States, this would be a 'state'.
      The state of the customer. Should be of the FIPS code form. For example California would be CA.
  note: 
    description: "You can store additional information about the candidate here such as your internal system's identifier for this individual. This will allow you to keep track of them."
