queryParameters: 
  date_of_birth: 
    description: The date of birth of the candidate in ISO form.
  name_first: 
    description: The legal first name of the customer.
  name_last: 
    description: The legal middle name of the customer.
  name_middle: 
    description: The legal middle name of the customer.
  passport: 
    description: The passport number of the individual being verified. This is only used for verifying non-US customers.
  ssn: 
    description: This can be either the last 4 digits of the US Social Security Number or the whole SSN.
