queryParameters: 
  limit: 
    description: Maximum number of objects in array. Default is 25. Maximum is 100.
    type: integer
    default: 25
  offset: 
    description: Object offset for pagination. Default is 0.
    type: integer
    default: 0
