get?: 
  headers: 
    Range: 
      description: |
        Downloads the specified range bytes of an object.
    If-Modified-Since: 
      description: |
        Return the object only if it has been modified since the specified time, otherwise return a 304 (not modified).
    If-Unmodified-Since: 
      description: |
        Return the object only if it has not been modified since the specified time, otherwise return a 412 (precondition failed).
    If-Match: 
      description: |
        Return the object only if its entity tag (ETag) is the same as the one specified, otherwise return a 412 (precondition failed).
    If-None-Match: 
      description: |
        Return the object only if its entity tag (ETag) is different from the one specified, otherwise return a 304 (not modified).
put?: 
  headers: 
    Cache-Control: 
      description: |
        Can be used to specify caching behavior along the request/reply chain
    Content-Disposition: 
      description: |
        Specifies presentational information for the object.
    Content-Encoding: 
      description: |
        Specifies what content encodings have been applied to the object and
        thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field.
    Content-Length: 
      description: |
        The size of the object, in bytes.
    Content-MD5: 
      description: |
        The base64-encoded 128-bit MD5 digest of the message (without the headers) according to RFC 1864. This header can be
        used as a message integrity check to verify that the data is the same data that was originally sent. Although it is optional,
        we recommend using the Content-MD5 mechanism as an end-to-end integrity check.
    Expires: 
      description: |
        The date and time at which the object is no longer cacheable.
    "x-amz-meta-{*}": 
      description: |
        Any header starting with this prefix is considered user metadata. It will be stored with the object and returned when you
        retrieve the object. The PUT request header is limited to 8 KB in size. Within the PUT request header, the user-defined
        metadata is limited to 2 KB in size. User-defined metadata is a set of key-value pairs. The size of user-defined metadata
        is measured by taking the sum of the number of bytes in the UTF-8 encoding of each key and value.
    x-amz-server-side-encryption: 
      description: |
        Specifies a server-side encryption algorithm to use when Amazon S3 creates an object.
      enum: [ AES256 ]
    x-amz-storage-class: 
      description: |
        RRS enables customers to reduce their costs by storing non-critical, reproducible data at lower levels of redundancy
        than Amazon S3's standard storage.
      enum: [ STANDARD , REDUCED_REDUNDANCY ]
      default: STANDARD
    x-amz-website-redirect-location: 
      description: |
        If the bucket is configured as a website, redirects requests for this object to another object in the same bucket or to an
        external URL. Amazon S3 stores the value of this header in the object metadata.
      pattern: "^(https?://|/).*$"
      maxLength: 2042
delete?: 
  headers: 
    x-amz-mfa: 
      description: |
        The value is the concatenation of the authentication device's serial number, a space, and the value displayed on your authentication device.
        Condition: Required to configure the versioning state if versioning is configured with MFA Delete enabled.
head?: 
  headers: 
    Range: 
      description: |
        Downloads the specified range bytes of an object.
    If-Modified-Since: 
      description: |
        Return the object only if it has been modified since the specified time, otherwise return a 304 (not modified).
    If-Unmodified-Since: 
      description: |
        Return the object only if it has not been modified since the specified time, otherwise return a 412 (precondition failed).
    If-Match: 
      description: |
        Return the object only if its entity tag (ETag) is the same as the one specified, otherwise return a 412 (precondition failed).
    If-None-Match: 
      description: |
        Return the object only if its entity tag (ETag) is different from the one specified, otherwise return a 304 (not modified).
options?: 
  headers: 
    Origin: 
      description: |
        Identifies the origin of the cross-origin request to Amazon S3.
      required: true
      example: http://www.example.com
    Access-Control-Request-Method: 
      description: |
        Identifies what HTTP method will be used in the actual request.
    Access-Control-Request-Headers: 
      description: |
        A comma-delimited list of HTTP headers that will be sent in the actual request.
        For example, to put an object with server-side encryption, this preflight request will determine if it can include the
        x-amz-server-side-encryption header with the request.
post?: 
usage: |
  Use this type for working with object's operations.
type: baseResource
description: |
  This is extented resource type for resources involved in operation with object.
  Inherits base resource and contains additonal headers
