queryParameters: 
  convert: 
    description: "Whether to convert this file to the corresponding Google Docs format. (Default: false)"
  ocr: 
    description: "Whether to attempt OCR on .jpg, .png, .gif, or .pdf uploads. (Default: false)"
  ocrLanguage: 
    description: If ocr is true, hints at the language to use. Valid values are ISO 639-1 codes.
  pinned: 
    description: |
      Whether to pin the head revision of the uploaded file. A file can have a maximum of 200 pinned revisions. (Default: false)
      Whether to pin the new revision. A file can have a maximum of 200 pinned revisions. (Default: false)
  timedTextLanguage: 
    description: The language of the timed text.
  timedTextTrackName: 
    description: The timed text track name.
  useContentAsIndexableText: 
    description: "Whether to use the content as indexable text. (Default: false)"
