usage: 'This type should be used for methods that allows to select one of the two states (the default and the "activated")'
type: meetupResource
description: <<resourcePathName>>
post: 
  description: 'Change the state to the "activated"'
delete: 
  description: Restore the default state
