usage: This type should be used for methods that allows to edit collections and its elements
type: meetupResource
description: The collection of <<resourcePathName>>
post: 
  description: Create a new <<resourcePathName | !singularize>>
