usage: This type should be used for methods that allows to edit elements of collections
type: meetupResource
description: The element of collection of <<resourcePathName>>
uriParameters: 
  id: 
    description: ":id in the path should be the <<resourcePathName>> id"
get: 
  description: Get a <<resourcePathName>> by id
post: 
  description: Edit a <<resourcePathName>> by id
delete: 
  description: Delete a <<resourcePathName>> by id
