queryParameters: 
  community_urlname: 
    description: 'Up to five URL paths, separated by commas. "urlname" or "container_id" is also required'
  community_id: 
    description: One or more IDs, separated by commas
