queryParameters: 
  description: 
    description: Description of this container
  facebook_urlname: 
    description: path name without slashes
  link: 
    description: must be a URL
  link_name: 
    description: Name of link
  name: 
    description: Name of this container
  twitter_urlname: 
    description: account name, no slash or @
