queryParameters: 
  comments: 
    description: 'Alert for each comment, "true" or "false"'
  rsvps: 
    description: 'Alert for each rsvp, "true" or "false"'
  updates: 
    description: 'Alert for updates to events, "true" or "false"'
