queryParameters: 
  after: 
    description: Return events scheduled after the specified date, formatted as described below
  before: 
    description: Return events scheduled before the specified date, formatted as described below
