description: Schema which requires Application ID and REST API Key
type: x-token-schema
describedBy: 
  headers: 
    Authorization: 
      required: true
      example: Token token=E7px6VVr3PVHZPJq51oa
