description: |
  Any API request requires your key. Authentication via headers parameters or query parameters.
type: x-ApiKey
describedBy: 
  queryParameters: 
    appId: 
      description: Authentication query parameters
    appKey: 
      description: Authentication query parameters
