post: 
  body: 
    application/json: 
      schema: copyFolder
      example: !include ../examples/copyFolder-example.json
  responses: 
    201: 
      description: A successful response contains a JSON representation.
