get?: 
  responses: 
    200: 
      body: 
        application/xml: 
        application/json: 
post?: 
  responses: 
    200: 
      body: 
        application/xml: 
        application/json: 
type: base
uriParameters: 
  mediaTypeSuffix: 
    description: empty value stands for XML
    enum: [ JSON , "" ]
