description: ""
type: OAuth 1.0
settings: 
  requestTokenUri: "{protocol}://{domain}/oauth/initiate"
  authorizationUri: "{protocol}://{domain}/oauth/oauth_authorize"
  tokenCredentialsUri: "{protocol}://{domain}/oauth/token"
