description: ""
type: OAuth 2.0
describedBy: 
  headers: 
    Authorization: 
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "access_token" queryParameters string parameter.
  queryParameters: 
    access_token: 
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "Authorization" header
settings: 
  authorizationUri: https://accounts.google.com/o/oauth2/auth
  accessTokenUri: https://accounts.google.com/o/oauth2/token
  authorizationGrants: [ code ]
  scopes: [ "https://mail.google.com/" ]
