queryParameters: 
  limit: 
    description: The number of iterations to return relative to the offset.
  offset: 
    description: "The offset of first iteration to return, relative to the set of iterations specified by 'scope', with zero being the first iteration in the scope. Defaults to zero. For the 'Done' scope, negative numbers can be passed, which specifies the number of iterations preceding the 'Current' iteration."
    type: integer
