type: x-zws-id-schema
describedBy: 
  queryParameters: 
    zws-id: 
      description: |
        The Zillow Web Service Identifier. Each subscriber to Zillow Web Services is uniquely
        identified by an ID sequence and every request to Web services requires this ID.
