body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      Password: 
        description: |
          The password that the username will use when when authenticating SIP requests.
          The password must be a minimum of 12 characters, contain at least 1 digit,
          and have mixed case. (eg "IWasAtTwilioCon2011")
        required: true
      Username: 
        description: |
          The username that will be passed when authenticating SIP requests.
          The username should be sent in response to Twilio's challenge of the initial INVITE.
          It can be up to 32 characters long.
        required: true
