body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      DateCreated: 
        description: |
          Only show <<type|!pluralize>> created on the given date. Should be formatted as YYYY-MM-DD. You can also specify inequality,
          such as DateCreated<=YYYY-MM-DD for <<type|!pluralize>> generated at or before midnight on a date,
          and DateCreated>=YYYY-MM-DD for <<type|!pluralize>> generated at or after midnight on a date.
