type: x-custom
describedBy: 
  headers: 
    Authorization: 
      description: Specifies the authentication scheme, account name, and signature. For more information, see Authentication for the Windows Azure Storage Services.
      required: true
