get?: 
  is: [ responseable ]
  description: |
    Returns summary information for all entities that match query parameters you provide. To get comprehensive information for a particular entity, first get the entity's id with the appropriate List endpoint, then provide the id to the corresponding Retrieve endpoint.
post?: 
  is: [ responseable ]
  description: |
    Creates and persists an entity of the corresponding type.
put?: 
  is: [ responseable ]
  description: |
    Modifies the existing entity that matches the identifier you provide.
delete?: 
  is: [ responseable ]
  description: |
    Deletes the existing entity that matches the identifier you provide.
