description: |
  If you are entering many records in a single API call then we recommend you utilise our new response format that shows validation errors for each record. The new response messages for validating bulk API calls would mean a breaking change so to utilise this functionality you'll need to append ?SummarizeErrors=false
queryParameters: 
  SummarizeErrors: 
    enum: [ true , false ]
