usage: Filter records by their modification date
description: |
  The ModifiedAfter filter is actually an HTTP header: 'If-Modified-Since'. A UTC timestamp (yyyy-mm-ddThh:mm:ss). Only contacts created or modified since this timestamp will be returned.
headers: 
  modifiedAfter: 
    example: "2009-11-12T00:00:00"
