usage: Order by any element returned
description: |
  A list of items can be returned in a specific order. To specify the ordering, append an order querystring to the endpoint URL.
queryParameters: 
  order: 
    description: |
      You can get results in descending order by using DESC parameter.
    example: EmailAddress%20DESC
