usage: |
  Use when requests require authentication.
description: |
  Headers for authentication.
headers: 
  Authorization: 
    description: |
      The information required for request authentication.
    required: true
  Date: 
    description: |
      The current date and time according to the requester. Example: Wed, 01 Mar 2006 12:00:00 GMT.
      When you specify the Authorization header, you must specify either the x-amz-date or the Date header
  x-amz-date: 
    description: |
      The current date and time according to the requester. Example: Wed, 01 Mar 2006 12:00:00 GMT.
      When you specify the Authorization header, you must specify either the x-amz-date or the Date header.
      If you specify both, the value specified for the x-amz-date header takes precedence.
