#%RAML 0.8
---
usage: |
  Use when request has a body
description: |
   This headers required used for PUTs and operations that load XML with optional integrity check
   **Note**
   "Content-MD5" - is optional, if it required for operation, please use trait with integrity-check
headers:
  Content-Length:
    description: |
      Length of the message (without the headers) according to RFC 2616.
    type: string
    required: true
  Content-MD5:
    description: |
      The base64 encoded 128-bit MD5 digest of the message (without the headers) according to RFC 1864.
      This header can be used as a message integrity check to verify that the data is the same data that was originally sent.
      Although it is optional, we recommend using the Content-MD5 mechanism as an end-to-end integrity check.
    type: string
