post?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: <<item>>
delete?: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: delete
          example: !include ../examples/delete.json
type: baseResource
get: 
  description: used to get information about item
  responses: 
    200: 
      body: 
        application/json: 
          schema: <<item>>