queryParameters: 
  sendEmail: 
    description: |
      Either "true" or "false" to  indicate whether or not to notify the user by email. Default is false.
      A boolean flag to indicate whether to send a welcome email or not. Defaults to false.
