queryParameters: 
  height: 
    description: An integer value that specifies the height of the generated image; the value must be between 100 and 300, inclusive.
    type: integer
  width: 
    description: An integer value that specifies the width of the generated image; the value must be between 200 and 600, inclusive
    type: integer
  chartDuration: 
    description: 'The duration of past data that needs to be shown in the chart. Valid values are "1year", "5years" and "10years". If unspecified, the value defaults to "1year".'
  unit-type: 
    description: 'A string value that specifies whether to show the percent change, parameter value of "percent," or dollar change, parameter value of "dollar"'
    required: true
