queryParameters: 
  callback: 
    description: The name of the JavaScript callback function used to process the returned JSON data. If specified, the returned JSON will be wrapped in a function call with the specified function name. This parameter is intended for use with dynamic script tags. The callback function is only used for JSON output.
  output: 
    description: "The type of output desired. Specify 'xml' for XML output and 'json' for JSON output. If omitted, 'xml' is assumed."
    default: xml
