queryParameters: 
  schedule: 
    description: The type of amortization schedule to return in the result set. If omitted, no table will be returned.
    enum: 
      - yearly
      - monthly
      - both
      - none
