queryParameters: 
  address: 
    description: The address of the property to search. This string should be URL encoded.
    required: true
  citystatezip: 
    description: The city+state combination and/or ZIP code for which to search. This string should be URL encoded. Note that giving both city and state is required. Using just one will not work.
    required: true
