description: |
  Body example for authorisation request:
  
  client_id=...&
  redirect_uri=...&
  response_type=code
  
  Bidy example for token request:
  
  POST Data
  client_id=...&
  client_secret=...&
  redirect_uri=...&
  code=...&
  grant_type=authorization_code
  
  All requests to the Buffer API must be made using HTTPS, with the access token provided in the HTTP Authorization header, request body or query string.
type: "OAuth 2.0"
describedBy: 
  queryParameters: 
    access_token:
      description: |
        OAuth 2.0 token for the current user.
    callback:
    key: 
      description: "API key."
      required: true
    prettyPrint:
      description: |
        Returns response with indentations and line breaks.
        Returns the response in a human-readable format if true.
        When this is false, it can reduce the response payload size, which might lead to better performance in some environments.
        default: true        
    quotaUser:
      description: |
        "Alternative to userIp."
        Lets you enforce per-user quotas from a server-side application even in cases when the user's IP address is unknown. This can occur, for example, with applications that run cron jobs on App Engine on a user's behalf.
        You can choose any arbitrary string that uniquely identifies a user, but it is limited to 40 characters.
        Overrides userIp if both are provided.
        Learn more about capping usage.    
    userIp:
      description: |
        IP address of the end user for whom the API call is being made.
        Lets you enforce per-user quotas when calling the API from a server-side application.
        Learn more about capping usage.
settings: 
  authorizationUri: "https://www.googleapis.com/auth/freebase"
  authorizationGrants: [ code ]
