description: |
  Authentication to the API occurs via HTTP Basic Auth. Provide your API key as the basic auth username. You do no
  need to provide a password.
type: Basic Authentication
describedBy: 
  headers: 
    Authorization: 
      description: |
        The Authorization field value consists of credentials
        containing the authentication information of the user agent for the
        realm of the resource being requested.
