queryParameters: 
  east: 
    description: bounding box, only features within the box are returned
    type: number
  west: 
    description: bounding box, only features within the box are returned
    type: number
  north: 
    description: bounding box, only features within the box are returned
    example: ""
  south: 
    description: bounding box, only features within the box are returned
    type: number
