post?: 
  responses: 
    204: 
      description: |
        No Content. Successful
delete?: 
  responses: 
    204: 
      description: |
        No Content. Successful
get?: 
  responses: 
    200: 
      description: Successful
