get?: 
post?: 
  body: 
    application/json: 
  responses: 
    200: 
      body: 
        application/json: 
put?: 
  body: 
    application/json: 
  responses: 
    200: 
      body: 
        application/json: 
delete?: 
  responses: 
    204: 
patch?: 
  body: 
    application/json: 
  responses: 
    200: 
      body: 
        application/json: 
is: [ commonParams ]
