get: 
  description: Get diagnostic information returned when an action link executes. Diagnostic information is given only for users who can access the action link.
  responses: 
    200: 
      body: 
        application/json: 
          schema: actionLinkDiagnosticResponse
head: 
  description: Get diagnostic information returned when an action link executes. Diagnostic information is given only for users who can access the action link.
  responses: 
    200: 
