head: 
  description: Returns all feed elements bookmarked by the context user.
  responses: 
    200: 
get: 
  description: Returns all feed elements bookmarked by the context user.
  queryParameters: 
    density: 
      description: |
        The density of the feed. One of these values:
        AllUpdates—Displays all updates from people and records the user follows and groups the user is a member of.
        FewerUpdates—Displays all updates from people and records the user follows and groups the user is a member of, but hides some system-generated updates from records.
        The default value is AllUpdates.
      enum: [ AllUpdates , FewerUpdates ]
      default: AllUpdates
      example: FewerUpdates
    elementsPerBundle: 
      description: |
        Maximum number of feed elements to include in a bundle. The value must be an integer between 0 and 10. The default value is 3.
        Note
        Bundled posts contain feed-tracked changes. In Salesforce1 downloadable apps, bundled posts are in record feeds only.
      type: integer
      default: 3
      example: 5
    page: 
      description: |
        A generated token that indicates the view of feed elements in the feed.
        Page tokens are returned as part of the response body, in one of the URL parameters, such as nextPageURL, for example:
        "nextPageUrl": 
        "/services/data/v34.0/
        chatter/feeds/news/005D0000001GLowIAN/feed-elements?page=2011-03-30T17:34:50Z,0D5D0000000DSv4KAG"
    pageSize: 
      description: "Specifies the number of elements per page. Valid values are between 1 and 100. If you don't specify a size, the default is 25."
      type: integer
      default: 25
      example: 5
    q: 
      description: |
        One or more keywords to search for in the body and comments of feed elements in this feed.
        The search string can contain wildcards and must contain at least two characters that aren’t wildcards. See Wildcards.
    recentComment​Count: 
      description: Maximum number of comments to include per feed element. The default value is 3. The maximum value is 25.
      type: integer
      default: 3
      example: 5
    sort: 
      description: |
        Specifies the order returned by the sort, such as by date created or last modified:
        CreatedDateDesc—Sorts by most recent creation date.
        LastModifiedDateDesc—Sorts by most recent activity.
        The default value is CreatedDescDate.
      enum: [ CreatedDescDate , LastModifiedDateDesc ]
      default: CreatedDescDate
      example: LastModifiedDateDesc
  responses: 
    200: 
      body: 
        application/json: 
          schema: feedElementPageResponse
