get: 
  description: Access the canvas capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: canvasCapabilityResponse
head: 
  description: Access the canvas capability of a feed element.
