get: 
  description: Access the enhanced link capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: enhancedLinkCapabilityResponse
head: 
  description: Access the enhanced link capability of a feed element.
  responses: 
    200: 
