get: 
  description: Access the dashboard component capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: dashboardComponentSnapshotCapabilityResponse
head: 
  description: Access the dashboard component capability of a feed element.
  responses: 
    200: 
