get: 
  description: Access the link capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: linkCapabilityResponse
head: 
  description: Access the link capability of a feed element.
  responses: 
    200: 
