head: 
  description: Access the content capability of a feed element.
  responses: 
    200: 
get: 
  description: Access the content capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: contentCapabilityResponse
