get: 
  description: Access the tracked changes capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: trackedChangesCapabilityResponse
head: 
  description: Access the tracked changes capability of a feed element.
  responses: 
    200: 
