get: 
  description: Access the recommendations capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: recommendationsCapabilityResponse
head: 
  description: Access the recommendations capability of a feed element.
  responses: 
    200: 
