get: 
  description: Access the approval capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: approvalCapabilityResponse
head: 
  description: Access the approval capability of a feed element.
  responses: 
    200: 
