get:
  description: Access question and answers for a feed element.
  responses:
    200:
      body:
        application/json:
          schema: questionAndAnswersCapabilityResponse
patch:
  description: Update question and answers on a feed element.
  body:
    application/json:
  responses:
    200:
      body:
        application/json:
          schema: questionAndAnswersCapabilityResponse
