get:
  description: Access a poll for a feed element.
  responses:
    200:
      body:
        application/json:
          schema: pollCapabilityResponse
patch:
  description: Create a poll, or vote on a poll.
  body:
    application/json: 
  responses:
    200:
      body:
        application/json:
          schema: pollCapabilityResponse
