get: 
  description: Get information about a comma-separated list of up to 500 feed elements. Errors for feed elements that can’t be loaded are returned in the results.
  responses: 
    200: 
      application/json: 
        schema: batchResultsResponse