get: 
  description: Access the associated actions capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: associatedActionsCapabilityResponse
head: 
  description: Access the associated actions capability of a feed element.
  responses: 
    200: 
