get: 
  description: Access the origin capability of a feed element. If a feed element has this capability, it was created by a feed action.
  responses: 
    200: 
      body: 
        application/json: 
          schema: originCapabilityResponse
head: 
  description: Access the origin capability of a feed element. If a feed element has this capability, it was created by a feed action.
  responses: 
    200: 
