get: 
  description: Indicates whether the context user can edit the feed element. Feed items are the only type of feed element that can be edited.
  responses: 
    200: 
      body: 
        application/json: 
          schema: feedEntityIsEditableResponse
