get: 
  description: Access the banner capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: bannerCapabilityResponse
head: 
  description: Access the banner capability of a feed element.
