get: 
  description: Access the case comment capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: caseCommentCapabilityResponse
head: 
  description: Access the case comment capability of a feed element.
  responses: 
    200: 
