get: 
  description: Access the email message capability of a feed element.
  responses: 
    200: 
      body: 
        application/json: 
          schema: emailMessageCapabilityResponse
head: 
  description: Access the email message capability of a feed element.
  responses: 
    200: 
