get: 
  description: |
    Information about a list of files, specified by file IDs. Get information about a list of files.
    The number of file IDs you can specify is limited by the length of the URL. In general, you can specify up to 100 file IDs in a comma-separated list.
  responses: 
    200: 
      body: 
        application/json: 
delete: 
  description: |
    Information about a list of files, specified by file IDs. Delete a list of files.
    The number of file IDs you can specify is limited by the length of the URL. In general, you can specify up to 100 file IDs in a comma-separated list.
  responses: 
    200: 
