post: 
  description: Post an announcement to a group.
  queryParameters: 
    expirationDate: 
      description: "The Salesforce UI displays an announcement until 11:59 p.m. on this date unless another announcement is posted first. The Salesforce UI ignores the time value in the expirationDate. However, you can use the time value to create your own display logic in your own UI."
      type: date
  body: 
    application/json: 
      schema: createGroupAnnouncementRequest
      example: !include examples/createGroupAnnouncementRequest-example.json
  responses: 
    200: 
      body: 
        application/json: 
          schema: announcementResponse
head: 
  description: Information about the announcements posted to the specified group.
  responses: 
    200: 
get: 
  description: Information about the announcements posted to the specified group.
  queryParameters: 
    page: 
      description: An integer specifying a page of items. The default value is 0, which returns the first page.
      type: integer
      default: 0
    pageSize: 
      description: "Specifies the number of items per page. Valid values are from 1 through 100. If you don't specify a size, the default is 25."
      type: integer
      default: 25
      example: 5
  responses: 
    200: 
      body: 
        application/json: 
          schema: announcementPageResponse
