get: 
  description: Returns a URL to the feed elements for all the groups the current, signed-in user is a member of.
  responses: 
    200: 
      body: 
        application/json: 
          schema: feedResponse
