head: 
  description: Returns up to five topics most recently used in the specified group.
  responses: 
    200: 
      body: 
        application/json: 
get: 
  description: Returns up to five topics most recently used in the specified group.
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicCollectionResponse
