head: 
  description: Get information about a group record.
  responses: 
    200: 
get: 
  description: Get information about a group record.
  responses: 
    200: 
      body: 
        application/json: 
          schema: groupRecordResponse
delete: 
  description: Remove the association between a record and a group.
  responses: 
    204: 
