head: 
  description: List of topics for the organization.
  responses: 
    200: 
get: 
  description: List of topics for the organization.
  queryParameters: 
    exactMatch: 
      description: Use with the q parameter and specify true to find a topic by its exact, case-insensitive name. Default value is false.
      type: boolean
      default: false
      example: true
    page: 
      description: An integer greater than 0 specifying a page of topics. The default value is zero.
      type: integer
      default: 0
      example: 5
    pageSize: 
      description: Specifies the number of items per page. Valid values are between 1 and 100. The default value is 25.
      type: integer
      default: 25
      example: 5
    q: 
      description: A query string to filter the results. The string must contain at least two characters, not including wildcards.
    sort: 
      description: |
        One of the following values:
        popularDesc—Sorts topics by popularity with the most popular first. This value is the default.
        alphaAsc—Sorts topics alphabetically.
      enum: [ alphaAsc , popularDesc ]
      default: popularDesc
      example: alphaAsc
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicCollectionResponse
