get: 
  description: A list of Chatter Answers zones in the organization. Get information about zones available to the context user.
  queryParameters: 
    page: 
      description: An integer specifying a page of items. The default value is 0, which returns the first page.
      type: integer
      default: 0
      example: 5
    pageSize: 
      description: Specifies the number of items per page. Valid values are between 1 and 250. The default value is 25.
      type: integer
      default: 25
      example: 5
  responses: 
    200: 
      body: 
        application/json: 
          schema: zonePageResponse
