get: 
  description: List of five topics most closely related to the specified topic.
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicCollectionResponse
head: 
  description: List of five topics most closely related to the specified topic.
  responses: 
    200: 
