head: 
  description: An endorsement. Get information about an endorsement.
  responses: 
    200: 
get: 
  description: An endorsement. Get information about an endorsement.
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicEndorsementResponse
delete: 
  description: An endorsement. Remove an endorsement.
  responses: 
    204: 
