head: 
  description: Get information about a topic.
  responses: 
    200: 
get: 
  description: Get information about a topic.
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicResponse
patch: 
  description: |
    Update a topic’s name or description, merge topics.
    Users with the “Edit Topics” or “Modify All Data” permission can edit topic names and descriptions. Users with the “Delete Topics” or “Modify All Data” permission can merge and delete topics.
  queryParameters: 
    description: 
      description: Text description of the topic
    idsToMerge: 
      description: List of up to five topic IDs to merge with the topic
    name: 
      description: |
        Name of the topic
        Use this property to change only the capitalization and spacing of the topic name.
  body: 
    application/json: 
  responses: 
    200: 
      body: 
        application/json: 
          schema: topicResponse
delete: 
  description: |
    Delete a topic.
    Users with the “Delete Topics” or “Modify All Data” permission can merge and delete topics.
  responses: 
    204: 
