head: 
  description: Returns information about the five groups that most recently contributed to the specified topic.
  responses: 
    200: 
get: 
  description: Returns information about the five groups that most recently contributed to the specified topic.
  responses: 
    200: 
      body: 
        application/json: 
          schema: groupPageResponse
