post: 
  body: 
    application/json: 
      schema: watchRequest
      example: !include ../examples/watchRequest-example.json
  responses: 
    201: 
      body: 
        application/json: 
          schema: watchResponse
          example: !include ../examples/watchResponse-example.json
