delete?: 
  responses: 
    204: 
post?: 
  responses: 
    200: 
      body: 
        application/xml: 
          schema: <<type>>-xml
        application/json: 
          schema: <<type>>
get?: 
  responses: 
    200: 
      body: 
        application/xml: 
          schema: <<type>>-xml
        application/json: 
          schema: <<type>>
put?: 
  responses: 
    200: 
      body: 
        application/xml: 
          schema: <<type>>-xml
        application/json: 
          schema: <<type>>
type: mediaTypeExt
