type: base
uriParameters: 
  mediaTypeExtension: 
    description: |
      By default, Twilio's REST API returns XML. You may obtain CSV, JSON or HTML by appending ".csv", ".json", or ".html".
    enum: 
      - .json
      - .csv
      - .html
