post?: 
  responses: 
    200: 
      description: Success!
    304: 
      description: There was no new data to return.
    400: 
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further. In API v1.1, requests withou
        authentication are considered invalid and will yield this response.
    401: 
      description: Authentication credentials were missing or incorrect.
    403: 
      description: |
        The request is understood, but it has been refused or access is no
        allowed. An accompanying error message will explain why. This code is
        used when requests are being denied due to update limits.
    404: 
      description: |
        The URI requested is invalid or the resource requested, such as a user,
        does not exists. Also returned when the requested format is not supported
        by the requested method.
    406: 
      description: |
        Returned by the Search API when an invalid format is specified in the
        request.
    410: 
      description: |
        This resource is gone. Used to indicate that an API endpoint has been
        turned off. For example: "The Twitter REST API v1 will soon stop
        functioning. Please migrate to API v1.1."
    420: 
      description: |
        Returned by the version 1 Search and Trends APIs when you are being rate
        limited.
    422: 
      description: |
        Returned when an image uploaded to POST account/update_profile_banner is
        unable to be processed.
    429: 
      description: |
        Returned in API v1.1 when a request cannot be served due to the
        application's rate limit having been exhausted for the resource. See Rate
        Limiting in API v1.1.
    500: 
      description: |
        Something is broken. Please post to the group so the Twitter team can
        investigate.
    502: 
      description: Twitter is down or being upgraded.
    503: 
      description: |
        The Twitter servers are up, but overloaded with requests. Try again later.
    504: 
      description: |
        The Twitter servers are up, but the request couldn't be serviced due to
        some failure within our stack. Try again later.
get?: 
  responses: 
    200: 
      description: Success!
    304: 
      description: There was no new data to return.
    400: 
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further. In API v1.1, requests withou
        authentication are considered invalid and will yield this response.
    401: 
      description: Authentication credentials were missing or incorrect.
    403: 
      description: |
        The request is understood, but it has been refused or access is no
        allowed. An accompanying error message will explain why. This code is
        used when requests are being denied due to update limits.
    404: 
      description: |
        The URI requested is invalid or the resource requested, such as a user,
        does not exists. Also returned when the requested format is not supported
        by the requested method.
    406: 
      description: |
        Returned by the Search API when an invalid format is specified in the
        request.
    410: 
      description: |
        This resource is gone. Used to indicate that an API endpoint has been
        turned off. For example: "The Twitter REST API v1 will soon stop
        functioning. Please migrate to API v1.1."
    420: 
      description: |
        Returned by the version 1 Search and Trends APIs when you are being rate
        limited.
    422: 
      description: |
        Returned when an image uploaded to POST account/update_profile_banner is
        unable to be processed.
    429: 
      description: |
        Returned in API v1.1 when a request cannot be served due to the
        application's rate limit having been exhausted for the resource. See Rate
        Limiting in API v1.1.
    500: 
      description: |
        Something is broken. Please post to the group so the Twitter team can
        investigate.
    502: 
      description: Twitter is down or being upgraded.
    503: 
      description: |
        The Twitter servers are up, but overloaded with requests. Try again later.
    504: 
      description: |
        The Twitter servers are up, but the request couldn't be serviced due to
        some failure within our stack. Try again later.
uriParameters: 
  mediaTypeExtension: 
    description: Use .json to specify application/json media type.
    enum: [ .json ]
