queryParameters: 
  screen_name: 
    description: |
      A comma separated list of screen names, up to 100 are allowed in a single
      request. You are strongly encouraged to use a POST for larger (up to
      100 screen names) requests.
      
      A comma separated list of screen names, up to 100 are allowed in a single
      request.
  user_id: 
    description: |
      A comma separated list of user IDs, up to 100 are allowed in a single
      request. You are strongly encouraged to use a POST for larger requests.
      
      A comma separated list of user IDs, up to 100 are allowed in a single
      request.
