queryParameters: 
  screen_name: 
    description: |
      The screen name of the user for whom to return results for.
      The screen name of the user for whom to return results for. Helpful for
      disambiguating when a valid screen name is also a user ID.
  user_id: 
    description: |
      The ID of the user for whom to return results for.
      The ID of the user for whom to return results for. Helpful for disambiguating
      when a valid user ID is also a valid screen name.
