queryParameters: 
  list_id: 
    description: The numerical id of the list.
    required: true
  slug: 
    description: |
      You can identify a list by its slug instead of its numerical id. If you
      decide to do so, note that you'll also have to specify the list owner
      using the owner_id or owner_screen_name parameters.
    required: true
