queryParameters: 
  delimited: 
    description: |
      Specifies whether messages should be length-delimited. See the delimited
      parameter documentation for more information.
  stall_warnings: 
    description: |
      Specifies whether stall warnings should be delivered. See the stall_warnings
      parameter documentation for more information.
