queryParameters: 
  exclude_replies: 
    description: |
      This parameter will prevent replies from appearing in the returned timeline.
      Using exclude_replies with the count parameter will mean you will receive
      up-to count tweets  this is because the count parameter retrieves tha
      many tweets before filtering out retweets and replies. This parameter is
      only supported for JSON and XML responses.
