queryParameters: 
  stringify_ids: 
    description: |
      Many programming environments will not consume our Tweet ids due to their
      size. Provide this option to have ids returned as strings instead. 
      This parameter is especially important to use in Javascript environments.
