body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      skip_status: 
        description: |
          When set to either true, t or 1 statuses will not be included in the
          returned user objects.
