body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      trim_user: 
        description: |
          When set to either true, t or 1, each tweet returned in a timeline will
          include a user object including only the status authors numerical ID.
          Omit this parameter to receive the complete user object.
