queryParameters: 
  contributor_details: 
    description: |
      This parameter enhances the contributors element of the status response
      to include the screen_name of the contributor. By default only the user_id
      of the contributor is included.
