queryParameters: 
  stringify_ids: 
    description: |
      Many programming environments will not consume our Tweet ids due to their
      size. Provide this option to have ids returned as strings instead. More
      about Twitter IDs, JSON and Snowflake.
      
      Many programming environments will not consume our ids due to their size.
      Provide this option to have ids returned as strings instead. Read more
      about Twitter IDs, JSON and Snowflake.
