queryParameters: 
  max_id: 
    description: |
      Returns results with an ID less than (that is, older than) or equal to
      the specified ID.
  since_id: 
    description: |
      Returns results with an ID greater than (that is, more recent than) the
      specified ID. There are limits to the number of Tweets which can be
      accessed through the API. If the limit of Tweets has occured since the
      since_id, the since_id will be forced to the oldest ID available.
