queryParameters: 
  "attribute:street_address": 
    description: |
      This parameter searches for places which have this given street address.
      There are other well-known, and application specific attributes available.
      Custom attributes are also permitted. Learn more about Place Attributes.
  contained_within: 
    description: |
      This is the place_id which you would like to restrict the search results
      to. Setting this value means only places within the given place_id will
      be found.
      Specify a place_id. For example, to scope all results to places within
      "San Francisco, CA USA", you would specify a place_id of "5a110d312052166f"
