queryParameters: 
  owner_id: 
    description: The user ID of the user who owns the list being requested by a slug.
  owner_screen_name: 
    description: The screen name of the user who owns the list being requested by a slug.
