queryParameters: 
  cursor: 
    description: |
      Breaks the results into pages. The number of items returned is not guaranteed 
      as some results can be filtered. If no cursor is provided, a value of -1 will be assumed, which is the
      first "page."
      The response from the API will include a previous_cursor and next_cursor
      to allow paging back and forth. See Using cursors to navigate collections
      for more information.
