queryParameters: 
  max: 
    description: |
      sort = rank => string
      sort = name => string
      sort = type => string
  min: 
    description: |
      sort = rank => string
      sort = name => string
      sort = type => string
  sort: 
    enum: 
      - rank
      - name
      - type
