queryParameters: 
  max: 
    description: |
      sort = rank => string
      sort = name => string
  min: 
    description: |
      sort = rank => string
      sort = name => string
  sort: 
    enum: [ rank , name ]
