queryParameters: 
  site: 
    description: |
      Each of these methods operates on a single site at a time, identified by the site parameter. This parameter can be the full domain name (ie. "stackoverflow.com"), or a short form identified by api_site_parameter on the site object.
    required: true
    example: stackoverflow
