queryParameters: 
  max: 
    description: |
      sort = activity => date
      sort = creation => date
      sort = votes => number
      sort = hot => none
      sort = week => none
      sort = month => none
      sort = relevance => none
  min: 
    description: |
      sort = activity => date
      sort = creation => date
      sort = votes => number
      sort = hot => none
      sort = week => none
      sort = month => none
      sort = relevance => none
  sort: 
    enum: 
      - activity
      - creation
      - votes
      - hot
      - week
      - month
      - relevance
