queryParameters: 
  max: 
    description: |
      sort = activity => date
      sort = creation => date
      sort = votes => number
      sort = relevance => none
  min: 
    description: |
      sort = activity => date
      sort = creation => date
      sort = votes => number
      sort = relevance => none
  sort: 
    enum: 
      - activity
      - creation
      - votes
      - relevance
