queryParameters: 
  max: 
    description: |
      sort = creation => date
      sort = approval => date
      sort = rejection => date
  min: 
    description: |
      sort = creation => date
      sort = approval => date
      sort = rejection => date
  sort: 
    enum: 
      - creation
      - approval
      - rejection
