queryParameters: 
  max: 
    description: |
      sort = creation => date
      sort = applied => number
      sort = activity => date
  min: 
    description: |
      sort = creation => date
      sort = applied => number
      sort = activity => date
  sort: 
    enum: 
      - creation
      - applied
      - activity
