queryParameters: 
  max: 
    description: |
      sort = popular => number
      sort = activity => date
      sort = name => string
  min: 
    description: |
      sort = popular => number
      sort = activity => date
      sort = name => string
  sort: 
    enum: 
      - popular
      - activity
      - name
