queryParameters: 
  max: 
    description: |
      sort = reputation => number
      sort = creation => date
      sort = name => string
      sort = modified => date
  min: 
    description: |
      sort = reputation => number
      sort = creation => date
      sort = name => string
      sort = modified => date
  sort: 
    enum: 
      - reputation
      - creation
      - name
      - modified
