#%RAML 0.8
title: GMail Media Upload
version: v1
baseUri: https://www.googleapis.com/upload/gmail/{version}/users
securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth_2_0.raml
schemas:
  - invalidCredentials: !include schemas/invalidCredentials-schema.json
  - notFound: !include schemas/notFound-schema.json
resourceTypes:
  - baseUpload: !include resourceTypes/baseUpload.raml
traits:
  - uploadMedia: !include traits/uploadMedia.raml
  - commonParams: !include traits/commonParams.raml
securedBy: [ oauth_2_0 ]
/{userId}: 
  /messages: 
    type: baseUpload
    post: 
      description: "Media upload request. Directly inserts a message into only this user's mailbox. Does not send a message."
      responses: 
        200: 
          body: 
            message/rfc822:
    /send: 
      type: baseUpload
      post: 
        description: "Media upload request. Sends the specified message to the recipients in the 'To', 'Cc', and 'Bcc' headers."
        responses: 
          200: 
            body: 
              message/rfc822:
    /import: 
      type: baseUpload
      post: 
        description: "Media upload request. Directly imports a message into only this user's mailbox, similar to receiving via SMTP. Does not send a message."
        responses: 
          200: 
            body: 
              message/rfc822:
  /drafts: 
    type: baseUpload
    post: 
      description: Media upload request. Creates a new draft with the DRAFT label.
      responses: 
        200: 
          body: 
            message/rfc822:
    /{id}: 
      type: baseUpload
      put: 
        description: "Media upload request. Replaces a draft's content."
        responses: 
          200: 
            body: 
              message/rfc822:
    /send: 
      type: baseUpload
      post: 
        description: "Media upload request. Sends the specified, existing draft to the recipients in the 'To', 'Cc', and 'Bcc' headers. "
        responses: 
          200: 
            body: 
              message/rfc822:
documentation: 
  - title: Headline
    content: !include docs/uploadApi/headline.md