body: 
  application/x-www-form-urlencoded: 
    formParameters: 
      description: 
        description: A description of the category
      name: 
        description: Name of the category
      parent: 
        description: ID of the parent category
