queryParameters: 
  http_envelope: 
    description: 'false: (default) true: Some environments (like in-browser Javascript or Flash) block or divert responses with a non-200 HTTP status code. Setting this parameter will force the HTTP status code to always be 200. The JSON response is wrapped in an "envelope" containing the "real" HTTP status code and headers.'
    type: boolean
    default: false
    example: true
  callback: 
    description: An optional JSONP callback function.
  pretty: 
    description: "false: (default) true: Output pretty JSON"
    type: boolean
    default: false
    example: true
