queryParameters: 
  context: 
    description: "display: (default) Formats the output as HTML for display. Shortcodes are parsed, paragraph tags are added, etc.. edit: Formats the output for editing. Shortcodes are left unparsed, significant whitespace is kept, etc.."
    enum: [ display , edit ]
    default: display
    example: edit
