queryParameters: 
  num_note_items: 
    description: "Number of items to include in notifications that contain multiple items Default: 9."
    type: integer
    default: 9
  fields: 
    description: "List of comma separated fields in the note object to return. Default: 'id,type,unread,noticon,body,subject,timestamp'."
    default: id,type,unread,noticon,body,subject,timestamp
