queryParameters: 
  page: 
    description: Return the Nth 1-indexed page of <<name>>. Takes precedence over the offset parameter.
    type: integer
    required: true
  offset: 
    description: 0-indexed offset.
    type: integer
    required: true
