queryParameters: 
  days: 
    description: "number of days to include in the query Default: 1."
    type: integer
    default: 1
    example: 7
  date: 
    description: the most recent day to include in results
    required: true
