get?: 
  responses: 
    400: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |4001|Missing or invalid 'time' parameter|
        |4002|Missing 'override' parameter|
        |4003|User Not Found|
        |4004|Invalid Override|
        |4005|Cannot Destroy Override|
put?: 
  responses: 
    400: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |4001|Missing or invalid 'time' parameter|
        |4002|Missing 'override' parameter|
        |4003|User Not Found|
        |4004|Invalid Override|
        |4005|Cannot Destroy Override|
post?: 
  responses: 
    400: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |4001|Missing or invalid 'time' parameter|
        |4002|Missing 'override' parameter|
        |4003|User Not Found|
        |4004|Invalid Override|
        |4005|Cannot Destroy Override|
delete?: 
  responses: 
    400: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |4001|Missing or invalid 'time' parameter|
        |4002|Missing 'override' parameter|
        |4003|User Not Found|
        |4004|Invalid Override|
        |4005|Cannot Destroy Override|
type: pagerDutyResource
