get?: 
  responses: 
    200?: 
      description: OK. The request was successful.
    201?: 
      description: Created. The request was successful and a new resource was created.
    204?: 
      description: No Content.  The request was successful. No content is returned.
    400?: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |Code|Message|
        |---|---|
        |2000|Internal Error|
        |2001|Invalid Input Provided|
        |2002|Arguments Caused Error|
        |2003|Missing Arguments|
        |2004|Invalid 'since' or 'until' Parameter Values|
        |2005|Invalid Query Date Range|
        |2006|Authentication Failed|
        |2007|Account Not Found|
        |2008|Account Locked|
        |2009|Only HTTPS Allowed For This Call|
        |2010|Access Denied|
        |2011|The action requires a 'requester_id' to be specified|
        |2012|Your account is expired and cannot use the API|
      body: 
        application/json: 
          schema: error
          example: !include ../examples/error.json
    500?: 
      description: Internal Server Error. Internal error occurred while processing request. Please try again.
put?: 
  responses: 
    200?: 
      description: OK. The request was successful.
    201?: 
      description: Created. The request was successful and a new resource was created.
    204?: 
      description: No Content.  The request was successful. No content is returned.
    400?: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |Code|Message|
        |---|---|
        |2000|Internal Error|
        |2001|Invalid Input Provided|
        |2002|Arguments Caused Error|
        |2003|Missing Arguments|
        |2004|Invalid 'since' or 'until' Parameter Values|
        |2005|Invalid Query Date Range|
        |2006|Authentication Failed|
        |2007|Account Not Found|
        |2008|Account Locked|
        |2009|Only HTTPS Allowed For This Call|
        |2010|Access Denied|
        |2011|The action requires a 'requester_id' to be specified|
        |2012|Your account is expired and cannot use the API|
      body: 
        application/json: 
          schema: error
          example: !include ../examples/error.json
    500?: 
      description: Internal Server Error. Internal error occurred while processing request. Please try again.
post?: 
  responses: 
    200?: 
      description: OK. The request was successful.
    201?: 
      description: Created. The request was successful and a new resource was created.
    204?: 
      description: No Content.  The request was successful. No content is returned.
    400?: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |Code|Message|
        |---|---|
        |2000|Internal Error|
        |2001|Invalid Input Provided|
        |2002|Arguments Caused Error|
        |2003|Missing Arguments|
        |2004|Invalid 'since' or 'until' Parameter Values|
        |2005|Invalid Query Date Range|
        |2006|Authentication Failed|
        |2007|Account Not Found|
        |2008|Account Locked|
        |2009|Only HTTPS Allowed For This Call|
        |2010|Access Denied|
        |2011|The action requires a 'requester_id' to be specified|
        |2012|Your account is expired and cannot use the API|
      body: 
        application/json: 
          schema: error
          example: !include ../examples/error.json
    500?: 
      description: Internal Server Error. Internal error occurred while processing request. Please try again.
delete?: 
  responses: 
    200?: 
      description: OK. The request was successful.
    201?: 
      description: Created. The request was successful and a new resource was created.
    204?: 
      description: No Content.  The request was successful. No content is returned.
    400?: 
      description: |
        Bad Request.
        Caller provided invalid arguments.
        Please review the response for error details.
        Retrying with the same arguments will not work.
        
        Error codes:
        |Code|Message|
        |---|---|
        |2000|Internal Error|
        |2001|Invalid Input Provided|
        |2002|Arguments Caused Error|
        |2003|Missing Arguments|
        |2004|Invalid 'since' or 'until' Parameter Values|
        |2005|Invalid Query Date Range|
        |2006|Authentication Failed|
        |2007|Account Not Found|
        |2008|Account Locked|
        |2009|Only HTTPS Allowed For This Call|
        |2010|Access Denied|
        |2011|The action requires a 'requester_id' to be specified|
        |2012|Your account is expired and cannot use the API|
      body: 
        application/json: 
          schema: error
          example: !include ../examples/error.json
    500?: 
      description: Internal Server Error. Internal error occurred while processing request. Please try again.
securedBy: [ basic , tokenSchema ]
