description: |
  Returns a static or animated satellite image for a given location.
  
  Response formats include GIF and PNG.
  
  #Request URL Format
  satellite requests follow may follow either of the following formats:
  
  GET http://api.wunderground.com/api/Your_Key/feature/image.format?params
  or
  GET http://api.wunderground.com/api/Your_Key/feature/q/query.format?params
  In the first format, you specify the geographical location of the image via the params options. In the second format, you may specify the location of the image by using the standard API location query format. If you use this second format, then you may override the location query via the position-oriented params options. For example, you may specify a city via query, but append a radius option to expand the scope of the image.
  
  #Examples
  http://api.wunderground.com/api/Your_Key/satellite/image.gif?maxlat=42.35&maxlon=-109.311&minlat=39.27&minlon=-114.644&width=600&height=480&key=sat_vis&basemap=1
  http://api.wunderground.com/api/Your_Key/satellite/image.gif?lat=38&lon=-96.4&radius=100&width=280&height=280&key=sat_ir4_bottom&basemap=1
  http://api.wunderground.com/api/Your_Key/satellite/q/KS/Topeka.gif?width=280&height=280&basemap=1
  http://api.wunderground.com/api/Your_Key/animatedsatellite/q/MI/Ann_Arbor.gif?basemap=1&timelabel=1&timelabel.y=10&num=5&delay=50
  http://api.wunderground.com/api/Your_Key/satellite/image.gif?maxlat=47.709&maxlon=-69.263&minlat=31.596&minlon=-97.388&width=640&height=480&key=sat_ir4_bottom>t=107&timelabel=1&timelabel.x=470&timelabel.y=41&proj=me
