description: |
  Returns a summary of the observed weather history for yesterday.
  
  #Examples:
  http://api.wunderground.com/api/Your_Key/yesterday/q/CA/San_Francisco.json
  (See description of the response.)
responses: 
  200: 
    description: |
      The response will be a JSON-encoded object.
      |name|description|
      |-|
      |history|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.dailysummary|Type: array. JSON type: array. The official API documentation provides no description. |
      |history.dailysummary.item|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.dailysummary.item.coolingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.coolingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.dailysummary.item.date.hour|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.mday|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.min|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.mon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.pretty|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.tzname|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.date.year|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.fog|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.gdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.hail|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.heatingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.heatingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.humidity|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxdewpti|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxdewptm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxhumidity|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxpressurei|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxpressurem|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxtempi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxtempm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxvisi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxvism|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxwspdi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.maxwspdm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meandewpti|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meandewptm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanpressurei|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanpressurem|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meantempi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meantempm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanvisi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanvism|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanwdird|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanwdire|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanwindspdi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.meanwindspdm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.mindewpti|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.mindewptm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minhumidity|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minpressurei|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minpressurem|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.mintempi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.mintempm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minvisi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minvism|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minwspdi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.minwspdm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodatecoolingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodatecoolingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodateheatingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodateheatingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodatesnowfalli|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.monthtodatesnowfallm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.precipi|Type: unknown. JSON type: string. Precipitation in inches. |
      |history.dailysummary.item.precipm|Type: unknown. JSON type: string. Precipitation in mm. |
      |history.dailysummary.item.precipsource|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.rain|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1jancoolingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1jancoolingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1julheatingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1julheatingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1julsnowfalli|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1julsnowfallm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1sepcoolingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1sepcoolingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1sepheatingdegreedays|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.since1sepheatingdegreedaysnormal|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.snow|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.snowdepthi|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.snowdepthm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.snowfalli|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.snowfallm|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.thunder|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.dailysummary.item.tornado|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.date.hour|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.mday|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.min|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.mon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.pretty|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.tzname|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.date.year|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations|Type: array. JSON type: array. The official API documentation provides no description. |
      |history.observations.item|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.observations.item.conds|Type: unknown. JSON type: string. See possible condition phrases below: http://www.wunderground.com/weather/api/d/docs?d=resources/phrase-glossary&MR=1#current_condition_phrases. |
      |history.observations.item.date|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.observations.item.date.hour|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.mday|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.min|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.mon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.pretty|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.tzname|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.date.year|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.dewpti|Type: unknown. JSON type: string. Duepoint in F. |
      |history.observations.item.dewptm|Type: unknown. JSON type: string. Dewpoint in C. |
      |history.observations.item.fog|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.hail|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.heatindexi|Type: unknown. JSON type: string. Heat Index F. |
      |history.observations.item.heatindexm|Type: unknown. JSON type: string. Heat index C. |
      |history.observations.item.hum|Type: unknown. JSON type: string. Humidity %. |
      |history.observations.item.icon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.metar|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.precipi|Type: unknown. JSON type: string. Precipitation in inches. |
      |history.observations.item.precipm|Type: unknown. JSON type: string. Precipitation in mm. |
      |history.observations.item.pressurei|Type: unknown. JSON type: string. Pressure in inHg. |
      |history.observations.item.pressurem|Type: unknown. JSON type: string. Pressure in mBar. |
      |history.observations.item.rain|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.snow|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.tempi|Type: unknown. JSON type: string. Temp in F. |
      |history.observations.item.tempm|Type: unknown. JSON type: string. Temp in C. |
      |history.observations.item.thunder|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.tornado|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.observations.item.utcdate.hour|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.mday|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.min|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.mon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.pretty|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.tzname|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.utcdate.year|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.observations.item.visi|Type: unknown. JSON type: string. Visability in Miles. |
      |history.observations.item.vism|Type: unknown. JSON type: string. Visibility in Km. |
      |history.observations.item.wdird|Type: unknown. JSON type: string. Wind direction in degrees. |
      |history.observations.item.wdire|Type: unknown. JSON type: string. Wind direction description (ie, SW, NNE). |
      |history.observations.item.wgusti|Type: unknown. JSON type: string. Wind gust in mph. |
      |history.observations.item.wgustm|Type: unknown. JSON type: string. Wind gust in kph. |
      |history.observations.item.windchilli|Type: unknown. JSON type: string. Wind chill in F. |
      |history.observations.item.windchillm|Type: unknown. JSON type: string. Wind chill in C. |
      |history.observations.item.wspdi|Type: unknown. JSON type: string. Windspeed in mph. |
      |history.observations.item.wspdm|Type: unknown. JSON type: string. WindSpeed kph. |
      |history.utcdate|Type: object. JSON type: object. The official API documentation provides no description. |
      |history.utcdate.hour|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.mday|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.min|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.mon|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.pretty|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.tzname|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |history.utcdate.year|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |response|Type: object. JSON type: object. The official API documentation provides no description. |
      |response.features|Type: object. JSON type: object. The official API documentation provides no description. |
      |response.features.yesterday|Type: unknown. JSON type: integer. The official API documentation provides no description. |
      |response.termsofService|Type: unknown. JSON type: string. The official API documentation provides no description. |
      |response.version|Type: unknown. JSON type: string. The official API documentation provides no description. |
    body: 
      application/json: 
        schema: yesterdaySchema
        example: !include ../examples/yesterday.json
      application/xml: 
