type: Basic Authentication
describedBy: 
  headers: 
    Authorization: 
      description: |
        The Authorization field value consists of credentials
        containing the authentication information of the user agent for the
        realm of the resource being requested.
